# Generated by Django 2.2.4 on 2020-05-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_posts',
            new_name='info',
        ),
    ]
