# Generated by Django 2.2.4 on 2020-05-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20200502_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='blog_posts',
        ),
    ]
