# Generated by Django 2.0.5 on 2020-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateFullName', models.CharField(max_length=20)),
                ('CandidateID', models.CharField(max_length=20)),
                ('CandidateContact', models.CharField(max_length=20)),
                ('CandidateAddress', models.CharField(max_length=20)),
            ],
        ),
    ]
